### ISSUE TITLE
Public todo list

### ISSUE THREAD

**Issue by rachmadaniHaryono** [CuddleBear92/Hydrus-Presets-and-Scripts#19]
This issue is here to combine todo / suggestions / recommendations for hydrus.

This is not official hydrus todo list, but to avoid any duplicate things that user want for hydrus

- [ ]  get items from 8chan suggestions thread https://8ch.net/hydrus/res/471.html
- [ ] get items from discord wishlist channel

The time of posting you get issues from should be logged. 
For example got everything between 01.01.2018-17.02.2018 as an example. This way its easier to track what has been pulled and not without checking for emotes.

**any added issue from the discord channel should be reacted with ✅ as a marker**

**Comment by CuddleBear92** [comment]
any added issue from the discord channel should be reacted with :white_check_mark: as a marker

**Comment by rachmadaniHaryono** [comment]
- [ ] Drag and drop windows with tag rules.
- [ ] Deriving tags from regex of other tags/namespace tags. 
- [ ] Tag sets with hotkeys
- [ ] Opaque window behind tag list in the corner so it doesn't get hidden by picture background
- [ ] Option to default certain mime types to be excluded from slideshow and only open externally
- [ ] Option to specify hamming distance in "find similar images",


>Drag and drop windows with tag rules.

Show two windows side by side and one window can be programmed with the rule "ADD tag foo" and the other one has the rule "REMOVE tag foo, ADD tag bar" and you can drag and drop files to them.


>Deriving tags from regex of other tags/namespace tags.

A file has the tag "filename:big_ugly_name" and we could regex that namespace for another tag.

dev: Drag and drop windows for tag rules is something I had never thought of, but I like it a lot. It could also do file uploading/exporting and other such duties. I want to add thumbnail dragging and dropping in future, so this could be a great extension of that code.

dev: Internal tag conversion is something that has been on my radar for a while– particularly for large but finicky jobs like adjusting page:n to page:n+1 for two hundred files. I haven't thought about what the dialog would look like for such a complicated and powerful tool, though. Maybe split it into two halves, like 
```
- LEFT: IF FILE MATCHES THESE PROPERTIES, 
- MIDDLE: DO THESE THINGS. 
- RIGHT: AFTER RUNNING THE SEARCH, THESE FILES MATCHED.
THIS IS WHAT THEY WILL LOOK LIKE AFTERWARDS.
YOU SURE YOU WANT TO DO IT?.
```
Perhaps this is just an powerful formalisation of the drag and drop idea above. Perhaps I need to write a scripting logic for the program first, so people can do these mass edits a bit easier?

>Tag sets with hotkeys.

save a set of tags under a hotkey so it's quick to add them to a file while filtering

dev: Allowing more complicated hotkeys could also use this scripting/macro language, and would be the easiest of the three things to do. I'll make a note to do that first.

>Option to default certain mime types to be excluded from slideshow and only open externally

will help with videos with odd codecs that don't preview in the slideshow correctly

dev: Most of the video and audio stuff was cobbled together, and I need to revisit it. Adding default action options for different mimes is a good idea.

>Option to specify hamming distance in "find similar images",

you can't change the option once it's in the filter window and you have to enter the hash manually in the "system:similar to" option

dev: Find similar is another thing I threw together. I've been meaning to expand it for a long time, but never got around to it. I would still like to add a 'find me all the dupes in my collection', but there are several big new things I need to create first. For now, I can definitely add a custom default distance for the menu entry.

>Opaque window behind tag list in the corner so it doesn't get hidden by picture background

dev: Making the media viewer's elements float above the image on mouse-move is high on my to-do list.
